import { BookOpen, Clock, Target } from 'lucide-react'
import type { TeachingPlanWeek } from '@/types/courseKit'

interface Props {
  teachingPlan: Record<string, unknown>[]
}

export function TeachingPlanSection({ teachingPlan }: Props) {
  if (teachingPlan.length === 0) {
    return (
      <div className="py-10 text-center text-sm text-gray-400">
        <BookOpen className="h-8 w-8 mx-auto mb-2 text-gray-200" />
        Teaching plan has not been generated yet. Use Generate with AI from the Draft state.
      </div>
    )
  }

  const weeks = teachingPlan as unknown as TeachingPlanWeek[]

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-gray-700">
          Teaching Plan ({weeks.length} week{weeks.length !== 1 ? 's' : ''})
        </h3>
        <span className="text-xs text-gray-400 italic">Read-only — generated by AI</span>
      </div>

      <div className="space-y-2">
        {weeks.map((week) => (
          <div
            key={week.week}
            className="rounded-lg border border-gray-200 px-4 py-3"
          >
            <div className="flex items-start gap-3">
              <span className="min-w-[3rem] text-sm font-bold text-gray-500 shrink-0">
                Wk {week.week}
              </span>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-gray-800">{week.topic}</p>

                {week.objectives.length > 0 && (
                  <div className="mt-1.5">
                    <p className="text-xs font-medium text-gray-500 flex items-center gap-1 mb-0.5">
                      <Target className="h-3 w-3" /> Objectives
                    </p>
                    <ul className="space-y-0.5 pl-4">
                      {week.objectives.map((obj, i) => (
                        <li key={i} className="text-xs text-gray-600 list-disc">{obj}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {week.activities.length > 0 && (
                  <div className="mt-1.5">
                    <p className="text-xs font-medium text-gray-500 mb-0.5">Activities</p>
                    <ul className="space-y-0.5 pl-4">
                      {week.activities.map((act, i) => (
                        <li key={i} className="text-xs text-gray-600 list-disc">{act}</li>
                      ))}
                    </ul>
                  </div>
                )}

                {week.co_references.length > 0 && (
                  <div className="flex items-center gap-1.5 mt-1.5 flex-wrap">
                    {week.co_references.map((co) => (
                      <span key={co} className="text-[10px] font-mono text-gray-500 bg-gray-100 px-1.5 py-0.5 rounded">
                        {co}
                      </span>
                    ))}
                  </div>
                )}
              </div>

              <span className="flex items-center gap-1 text-xs text-gray-400 shrink-0">
                <Clock className="h-3.5 w-3.5" />
                {week.hours}h
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
