{{- if and .Values.whisper.enabled .Values.whisper.keda.enabled }}
{{- $redisAddr := .Values.keda.redisAddress }}
{{- if .Values.redis.enabled }}
{{- $redisAddr = printf "%s:6379" (include "vidya.componentName" (list . "redis")) }}
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "vidya.componentName" (list . "whisper") }}
  labels:
    {{- include "vidya.componentLabels" (list . "whisper") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vidya.componentName" (list . "whisper") }}
  minReplicaCount: {{ .Values.whisper.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.whisper.keda.maxReplicaCount }}
  cooldownPeriod: {{ .Values.whisper.keda.cooldownPeriod }}
  pollingInterval: {{ .Values.whisper.keda.pollingInterval }}
  triggers:
    - type: redis
      metadata:
        address: {{ $redisAddr | quote }}
        listName: {{ .Values.whisper.keda.queueName | quote }}
        listLength: {{ .Values.whisper.keda.queueLength | quote }}
        databaseIndex: {{ .Values.keda.redisDatabaseIndex | quote }}
        enableTLS: {{ .Values.keda.redisEnableTLS | quote }}
      authenticationRef:
        name: {{ include "vidya.fullname" . }}-redis-triggerauth
{{- end }}
