import enum
import uuid

from sqlalchemy import Column, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.postgresql import JSONB, UUID

from app.database import Base


class AuditEventType(str, enum.Enum):
    # Tenant auth flows
    AUTH_LOGIN_SUCCESS               = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILURE               = "AUTH_LOGIN_FAILURE"
    AUTH_LOGOUT                      = "AUTH_LOGOUT"
    AUTH_LOGOUT_ALL                  = "AUTH_LOGOUT_ALL"
    AUTH_TOKEN_REFRESH               = "AUTH_TOKEN_REFRESH"
    AUTH_TOKEN_REUSE_DETECTED        = "AUTH_TOKEN_REUSE_DETECTED"
    AUTH_PASSWORD_RESET_REQUESTED    = "AUTH_PASSWORD_RESET_REQUESTED"
    AUTH_PASSWORD_RESET_OTP_FAILED   = "AUTH_PASSWORD_RESET_OTP_FAILED"
    AUTH_PASSWORD_RESET_VERIFIED     = "AUTH_PASSWORD_RESET_VERIFIED"
    AUTH_PASSWORD_RESET_COMPLETED    = "AUTH_PASSWORD_RESET_COMPLETED"

    # Platform auth flows (SUPER_ADMIN)
    PLATFORM_LOGIN_SUCCESS             = "PLATFORM_LOGIN_SUCCESS"
    PLATFORM_LOGIN_FAILURE             = "PLATFORM_LOGIN_FAILURE"
    PLATFORM_LOGOUT                    = "PLATFORM_LOGOUT"
    PLATFORM_LOGOUT_ALL                = "PLATFORM_LOGOUT_ALL"
    PLATFORM_TOKEN_REFRESH             = "PLATFORM_TOKEN_REFRESH"
    PLATFORM_TOKEN_REUSE_DETECTED      = "PLATFORM_TOKEN_REUSE_DETECTED"
    PLATFORM_PASSWORD_RESET_REQUESTED  = "PLATFORM_PASSWORD_RESET_REQUESTED"
    PLATFORM_PASSWORD_RESET_OTP_FAILED = "PLATFORM_PASSWORD_RESET_OTP_FAILED"
    PLATFORM_PASSWORD_RESET_VERIFIED   = "PLATFORM_PASSWORD_RESET_VERIFIED"
    PLATFORM_PASSWORD_RESET_COMPLETED  = "PLATFORM_PASSWORD_RESET_COMPLETED"

    # User management (tenant-scoped)
    USER_CREATED      = "USER_CREATED"
    USER_UPDATED      = "USER_UPDATED"
    USER_DEACTIVATED  = "USER_DEACTIVATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"

    # Tenant management (platform-level)
    TENANT_PROVISIONED = "TENANT_PROVISIONED"
    TENANT_UPDATED     = "TENANT_UPDATED"
    TENANT_DEACTIVATED = "TENANT_DEACTIVATED"

    # Storage operations (tenant-scoped)
    STORAGE_ASSET_CREATED    = "STORAGE_ASSET_CREATED"
    STORAGE_ASSET_DOWNLOADED = "STORAGE_ASSET_DOWNLOADED"
    STORAGE_ASSET_DELETED    = "STORAGE_ASSET_DELETED"

    # Program structure — M01
    PROGRAM_CREATED              = "PROGRAM_CREATED"
    PROGRAM_UPDATED              = "PROGRAM_UPDATED"
    PROGRAM_DELETED              = "PROGRAM_DELETED"
    PROGRAM_GENERATION_QUEUED    = "PROGRAM_GENERATION_QUEUED"
    PROGRAM_GENERATION_COMPLETED = "PROGRAM_GENERATION_COMPLETED"
    PROGRAM_GENERATION_FAILED    = "PROGRAM_GENERATION_FAILED"
    PROGRAM_APPROVED             = "PROGRAM_APPROVED"
    PROGRAM_REJECTED             = "PROGRAM_REJECTED"
    PROGRAM_FORKED               = "PROGRAM_FORKED"
    PROGRAM_COURSE_ADDED         = "PROGRAM_COURSE_ADDED"
    PROGRAM_COURSE_UPDATED       = "PROGRAM_COURSE_UPDATED"
    PROGRAM_COURSE_DELETED       = "PROGRAM_COURSE_DELETED"
    PROGRAM_OUTCOME_ADDED        = "PROGRAM_OUTCOME_ADDED"
    PROGRAM_OUTCOME_UPDATED      = "PROGRAM_OUTCOME_UPDATED"
    PROGRAM_OUTCOME_DELETED      = "PROGRAM_OUTCOME_DELETED"
    PROGRAM_EXPORT_REQUESTED     = "PROGRAM_EXPORT_REQUESTED"
    PROGRAM_EXPORT_COMPLETED     = "PROGRAM_EXPORT_COMPLETED"
    PROGRAM_EXPORT_FAILED        = "PROGRAM_EXPORT_FAILED"

    # Syllabus — M02 lifecycle
    SYLLABUS_CREATED = "SYLLABUS_CREATED"
    SYLLABUS_UPDATED = "SYLLABUS_UPDATED"
    SYLLABUS_DELETED = "SYLLABUS_DELETED"

    # Syllabus — M02 state transitions
    SYLLABUS_GENERATION_QUEUED = "SYLLABUS_GENERATION_QUEUED"
    SYLLABUS_APPROVED          = "SYLLABUS_APPROVED"
    SYLLABUS_REJECTED          = "SYLLABUS_REJECTED"
    SYLLABUS_LOCKED            = "SYLLABUS_LOCKED"
    SYLLABUS_UNLOCKED          = "SYLLABUS_UNLOCKED"
    SYLLABUS_FORKED            = "SYLLABUS_FORKED"

    # Syllabus — M02 AI generation tasks (added in STEP-07; kept here for completeness)
    SYLLABUS_GENERATION_COMPLETED  = "SYLLABUS_GENERATION_COMPLETED"
    SYLLABUS_GENERATION_FAILED     = "SYLLABUS_GENERATION_FAILED"
    REFERENCE_ENRICHMENT_COMPLETED = "REFERENCE_ENRICHMENT_COMPLETED"
    REFERENCE_ENRICHMENT_FAILED    = "REFERENCE_ENRICHMENT_FAILED"

    # Syllabus — M02 course outcomes
    SYLLABUS_CO_ADDED   = "SYLLABUS_CO_ADDED"
    SYLLABUS_CO_UPDATED = "SYLLABUS_CO_UPDATED"
    SYLLABUS_CO_DELETED = "SYLLABUS_CO_DELETED"

    # Syllabus — M02 CO-PO mappings
    SYLLABUS_COPO_MAPPING_UPDATED = "SYLLABUS_COPO_MAPPING_UPDATED"

    # Syllabus — M02 units
    SYLLABUS_UNIT_ADDED   = "SYLLABUS_UNIT_ADDED"
    SYLLABUS_UNIT_UPDATED = "SYLLABUS_UNIT_UPDATED"
    SYLLABUS_UNIT_DELETED = "SYLLABUS_UNIT_DELETED"

    # Syllabus — M02 references
    SYLLABUS_REFERENCE_ADDED     = "SYLLABUS_REFERENCE_ADDED"
    SYLLABUS_REFERENCE_UPDATED   = "SYLLABUS_REFERENCE_UPDATED"
    SYLLABUS_REFERENCE_DELETED   = "SYLLABUS_REFERENCE_DELETED"
    SYLLABUS_REFERENCE_CONFIRMED = "SYLLABUS_REFERENCE_CONFIRMED"

    # Syllabus — M02 export
    SYLLABUS_EXPORT_REQUESTED = "SYLLABUS_EXPORT_REQUESTED"
    SYLLABUS_EXPORT_COMPLETED = "SYLLABUS_EXPORT_COMPLETED"
    SYLLABUS_EXPORT_FAILED    = "SYLLABUS_EXPORT_FAILED"

    # Course Kit — M03 lifecycle
    COURSE_KIT_CREATED = "COURSE_KIT_CREATED"
    COURSE_KIT_UPDATED = "COURSE_KIT_UPDATED"
    COURSE_KIT_DELETED = "COURSE_KIT_DELETED"

    # Course Kit — M03 AI generation
    COURSE_KIT_GENERATION_QUEUED    = "COURSE_KIT_GENERATION_QUEUED"
    COURSE_KIT_GENERATION_COMPLETED = "COURSE_KIT_GENERATION_COMPLETED"
    COURSE_KIT_GENERATION_FAILED    = "COURSE_KIT_GENERATION_FAILED"

    # Course Kit — M03 state transitions
    COURSE_KIT_PUBLISHED = "COURSE_KIT_PUBLISHED"
    COURSE_KIT_ARCHIVED  = "COURSE_KIT_ARCHIVED"
    COURSE_KIT_FORKED    = "COURSE_KIT_FORKED"

    # Course Kit — M03 slides
    COURSE_KIT_SLIDE_ADDED    = "COURSE_KIT_SLIDE_ADDED"
    COURSE_KIT_SLIDE_UPDATED  = "COURSE_KIT_SLIDE_UPDATED"
    COURSE_KIT_SLIDE_DELETED  = "COURSE_KIT_SLIDE_DELETED"
    COURSE_KIT_SLIDES_REORDERED = "COURSE_KIT_SLIDES_REORDERED"

    # Course Kit — M03 quizlets
    COURSE_KIT_QUIZLET_ADDED   = "COURSE_KIT_QUIZLET_ADDED"
    COURSE_KIT_QUIZLET_UPDATED = "COURSE_KIT_QUIZLET_UPDATED"
    COURSE_KIT_QUIZLET_DELETED = "COURSE_KIT_QUIZLET_DELETED"

    # Course Kit — M03 assignments
    COURSE_KIT_ASSIGNMENT_ADDED   = "COURSE_KIT_ASSIGNMENT_ADDED"
    COURSE_KIT_ASSIGNMENT_UPDATED = "COURSE_KIT_ASSIGNMENT_UPDATED"
    COURSE_KIT_ASSIGNMENT_DELETED = "COURSE_KIT_ASSIGNMENT_DELETED"

    # Course Kit — M03 export (consumed by STEP-11)
    COURSE_KIT_EXPORT_REQUESTED = "COURSE_KIT_EXPORT_REQUESTED"
    COURSE_KIT_EXPORT_COMPLETED = "COURSE_KIT_EXPORT_COMPLETED"
    COURSE_KIT_EXPORT_FAILED    = "COURSE_KIT_EXPORT_FAILED"


class AuditLog(Base):
    __tablename__ = "audit_logs"
    __table_args__ = (
        Index("ix_audit_logs_tenant_created",  "tenant_id",     "created_at"),
        Index("ix_audit_logs_event_created",   "event_type",    "created_at"),
        Index("ix_audit_logs_actor_created",   "actor_user_id", "created_at"),
        Index("ix_audit_logs_created",         "created_at"),
        {"schema": "public"},
    )

    id            = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    event_type    = Column(String, nullable=False)
    actor_user_id = Column(UUID(as_uuid=True), nullable=True)
    actor_role    = Column(String, nullable=True)
    tenant_id     = Column(
        UUID(as_uuid=True),
        ForeignKey("public.tenants.id", ondelete="SET NULL"),
        nullable=True,
    )
    schema_name   = Column(String, nullable=True)
    target_entity = Column(String, nullable=True)
    target_id     = Column(String, nullable=True)
    metadata_     = Column("metadata", JSONB, nullable=True)
    ip_address    = Column(String, nullable=True)
    user_agent    = Column(String, nullable=True)
    created_at    = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
