import enum
import uuid

from sqlalchemy import Column, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.postgresql import JSONB, UUID

from app.database import Base

# Side-effect import: registers Tenant (public.tenants) in Base.metadata.
# AuditLog.tenant_id carries ForeignKey("public.tenants.id"), which SQLAlchemy
# resolves during configure_mappers(). In Celery worker processes the FastAPI
# app (and its routers) is never loaded, so auth models are never imported and
# public.tenants is absent from Base.metadata — causing NoReferencedTableError.
# This import is the canonical fix; it must stay here, adjacent to the FK.
import app.core.auth.models  # noqa: F401


class AuditEventType(str, enum.Enum):
    # Tenant auth flows
    AUTH_LOGIN_SUCCESS               = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILURE               = "AUTH_LOGIN_FAILURE"
    AUTH_LOGOUT                      = "AUTH_LOGOUT"
    AUTH_LOGOUT_ALL                  = "AUTH_LOGOUT_ALL"
    AUTH_TOKEN_REFRESH               = "AUTH_TOKEN_REFRESH"
    AUTH_TOKEN_REUSE_DETECTED        = "AUTH_TOKEN_REUSE_DETECTED"
    AUTH_PASSWORD_RESET_REQUESTED    = "AUTH_PASSWORD_RESET_REQUESTED"
    AUTH_PASSWORD_RESET_OTP_FAILED   = "AUTH_PASSWORD_RESET_OTP_FAILED"
    AUTH_PASSWORD_RESET_VERIFIED     = "AUTH_PASSWORD_RESET_VERIFIED"
    AUTH_PASSWORD_RESET_COMPLETED    = "AUTH_PASSWORD_RESET_COMPLETED"
    AUTH_PASSWORD_CHANGED            = "AUTH_PASSWORD_CHANGED"

    # Platform auth flows (SUPER_ADMIN)
    PLATFORM_LOGIN_SUCCESS             = "PLATFORM_LOGIN_SUCCESS"
    PLATFORM_LOGIN_FAILURE             = "PLATFORM_LOGIN_FAILURE"
    PLATFORM_LOGOUT                    = "PLATFORM_LOGOUT"
    PLATFORM_LOGOUT_ALL                = "PLATFORM_LOGOUT_ALL"
    PLATFORM_TOKEN_REFRESH             = "PLATFORM_TOKEN_REFRESH"
    PLATFORM_TOKEN_REUSE_DETECTED      = "PLATFORM_TOKEN_REUSE_DETECTED"
    PLATFORM_PASSWORD_RESET_REQUESTED  = "PLATFORM_PASSWORD_RESET_REQUESTED"
    PLATFORM_PASSWORD_RESET_OTP_FAILED = "PLATFORM_PASSWORD_RESET_OTP_FAILED"
    PLATFORM_PASSWORD_RESET_VERIFIED   = "PLATFORM_PASSWORD_RESET_VERIFIED"
    PLATFORM_PASSWORD_RESET_COMPLETED  = "PLATFORM_PASSWORD_RESET_COMPLETED"

    # Super Admin profile management
    PLATFORM_PROFILE_UPDATED  = "PLATFORM_PROFILE_UPDATED"
    PLATFORM_EMAIL_CHANGED    = "PLATFORM_EMAIL_CHANGED"
    PLATFORM_PASSWORD_CHANGED = "PLATFORM_PASSWORD_CHANGED"
    PLATFORM_BRANDING_UPDATED = "PLATFORM_BRANDING_UPDATED"

    # User management (tenant-scoped)
    USER_CREATED      = "USER_CREATED"
    USER_UPDATED      = "USER_UPDATED"
    USER_DEACTIVATED  = "USER_DEACTIVATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"

    # Tenant management (platform-level)
    TENANT_PROVISIONED          = "TENANT_PROVISIONED"
    TENANT_UPDATED              = "TENANT_UPDATED"
    TENANT_DEACTIVATED          = "TENANT_DEACTIVATED"
    TENANT_ARCHIVED             = "TENANT_ARCHIVED"
    TENANT_REACTIVATED          = "TENANT_REACTIVATED"
    TENANT_DELETED              = "TENANT_DELETED"
    TENANT_RESTORED             = "TENANT_RESTORED"
    TENANT_PERMANENTLY_DELETED  = "TENANT_PERMANENTLY_DELETED"

    # Storage operations (tenant-scoped)
    STORAGE_ASSET_CREATED    = "STORAGE_ASSET_CREATED"
    STORAGE_ASSET_DOWNLOADED = "STORAGE_ASSET_DOWNLOADED"
    STORAGE_ASSET_DELETED    = "STORAGE_ASSET_DELETED"

    # Program structure — M01
    PROGRAM_CREATED              = "PROGRAM_CREATED"
    PROGRAM_UPDATED              = "PROGRAM_UPDATED"
    PROGRAM_DELETED              = "PROGRAM_DELETED"
    PROGRAM_GENERATION_QUEUED    = "PROGRAM_GENERATION_QUEUED"
    PROGRAM_GENERATION_COMPLETED = "PROGRAM_GENERATION_COMPLETED"
    PROGRAM_GENERATION_FAILED    = "PROGRAM_GENERATION_FAILED"
    PROGRAM_APPROVED             = "PROGRAM_APPROVED"
    PROGRAM_REJECTED             = "PROGRAM_REJECTED"
    PROGRAM_FORKED               = "PROGRAM_FORKED"
    PROGRAM_COURSE_ADDED         = "PROGRAM_COURSE_ADDED"
    PROGRAM_COURSE_UPDATED       = "PROGRAM_COURSE_UPDATED"
    PROGRAM_COURSE_DELETED       = "PROGRAM_COURSE_DELETED"
    PROGRAM_OUTCOME_ADDED        = "PROGRAM_OUTCOME_ADDED"
    PROGRAM_OUTCOME_UPDATED      = "PROGRAM_OUTCOME_UPDATED"
    PROGRAM_OUTCOME_DELETED      = "PROGRAM_OUTCOME_DELETED"
    PROGRAM_EXPORT_REQUESTED     = "PROGRAM_EXPORT_REQUESTED"
    PROGRAM_EXPORT_COMPLETED     = "PROGRAM_EXPORT_COMPLETED"
    PROGRAM_EXPORT_FAILED        = "PROGRAM_EXPORT_FAILED"

    # Syllabus — M02 lifecycle
    SYLLABUS_CREATED = "SYLLABUS_CREATED"
    SYLLABUS_UPDATED = "SYLLABUS_UPDATED"
    SYLLABUS_DELETED = "SYLLABUS_DELETED"

    # Syllabus — M02 state transitions
    SYLLABUS_GENERATION_QUEUED = "SYLLABUS_GENERATION_QUEUED"
    SYLLABUS_APPROVED          = "SYLLABUS_APPROVED"
    SYLLABUS_REJECTED          = "SYLLABUS_REJECTED"
    SYLLABUS_LOCKED            = "SYLLABUS_LOCKED"
    SYLLABUS_UNLOCKED          = "SYLLABUS_UNLOCKED"
    SYLLABUS_FORKED            = "SYLLABUS_FORKED"

    # Syllabus — M02 AI generation tasks (added in STEP-07; kept here for completeness)
    SYLLABUS_GENERATION_COMPLETED  = "SYLLABUS_GENERATION_COMPLETED"
    SYLLABUS_GENERATION_FAILED     = "SYLLABUS_GENERATION_FAILED"
    REFERENCE_ENRICHMENT_COMPLETED = "REFERENCE_ENRICHMENT_COMPLETED"
    REFERENCE_ENRICHMENT_FAILED    = "REFERENCE_ENRICHMENT_FAILED"

    # Syllabus — M02 course outcomes
    SYLLABUS_CO_ADDED   = "SYLLABUS_CO_ADDED"
    SYLLABUS_CO_UPDATED = "SYLLABUS_CO_UPDATED"
    SYLLABUS_CO_DELETED = "SYLLABUS_CO_DELETED"

    # Syllabus — M02 CO-PO mappings
    SYLLABUS_COPO_MAPPING_UPDATED = "SYLLABUS_COPO_MAPPING_UPDATED"

    # Syllabus — M02 units
    SYLLABUS_UNIT_ADDED   = "SYLLABUS_UNIT_ADDED"
    SYLLABUS_UNIT_UPDATED = "SYLLABUS_UNIT_UPDATED"
    SYLLABUS_UNIT_DELETED = "SYLLABUS_UNIT_DELETED"

    # Syllabus — M02 references
    SYLLABUS_REFERENCE_ADDED     = "SYLLABUS_REFERENCE_ADDED"
    SYLLABUS_REFERENCE_UPDATED   = "SYLLABUS_REFERENCE_UPDATED"
    SYLLABUS_REFERENCE_DELETED   = "SYLLABUS_REFERENCE_DELETED"
    SYLLABUS_REFERENCE_CONFIRMED = "SYLLABUS_REFERENCE_CONFIRMED"

    # Syllabus — M02 export
    SYLLABUS_EXPORT_REQUESTED = "SYLLABUS_EXPORT_REQUESTED"
    SYLLABUS_EXPORT_COMPLETED = "SYLLABUS_EXPORT_COMPLETED"
    SYLLABUS_EXPORT_FAILED    = "SYLLABUS_EXPORT_FAILED"

    # Course Kit — M03 lifecycle
    COURSE_KIT_CREATED = "COURSE_KIT_CREATED"
    COURSE_KIT_UPDATED = "COURSE_KIT_UPDATED"
    COURSE_KIT_DELETED = "COURSE_KIT_DELETED"

    # Course Kit — M03 AI generation
    COURSE_KIT_GENERATION_QUEUED    = "COURSE_KIT_GENERATION_QUEUED"
    COURSE_KIT_GENERATION_COMPLETED = "COURSE_KIT_GENERATION_COMPLETED"
    COURSE_KIT_GENERATION_FAILED    = "COURSE_KIT_GENERATION_FAILED"

    # Course Kit — M03 state transitions
    COURSE_KIT_PUBLISHED = "COURSE_KIT_PUBLISHED"
    COURSE_KIT_ARCHIVED  = "COURSE_KIT_ARCHIVED"
    COURSE_KIT_FORKED    = "COURSE_KIT_FORKED"

    # Course Kit — M03 slides
    COURSE_KIT_SLIDE_ADDED    = "COURSE_KIT_SLIDE_ADDED"
    COURSE_KIT_SLIDE_UPDATED  = "COURSE_KIT_SLIDE_UPDATED"
    COURSE_KIT_SLIDE_DELETED  = "COURSE_KIT_SLIDE_DELETED"
    COURSE_KIT_SLIDES_REORDERED = "COURSE_KIT_SLIDES_REORDERED"

    # Course Kit — M03 quizlets
    COURSE_KIT_QUIZLET_ADDED   = "COURSE_KIT_QUIZLET_ADDED"
    COURSE_KIT_QUIZLET_UPDATED = "COURSE_KIT_QUIZLET_UPDATED"
    COURSE_KIT_QUIZLET_DELETED = "COURSE_KIT_QUIZLET_DELETED"

    # Course Kit — M03 assignments
    COURSE_KIT_ASSIGNMENT_ADDED   = "COURSE_KIT_ASSIGNMENT_ADDED"
    COURSE_KIT_ASSIGNMENT_UPDATED = "COURSE_KIT_ASSIGNMENT_UPDATED"
    COURSE_KIT_ASSIGNMENT_DELETED = "COURSE_KIT_ASSIGNMENT_DELETED"

    # Course Kit — M03 export (consumed by STEP-11)
    COURSE_KIT_EXPORT_REQUESTED = "COURSE_KIT_EXPORT_REQUESTED"
    COURSE_KIT_EXPORT_COMPLETED = "COURSE_KIT_EXPORT_COMPLETED"
    COURSE_KIT_EXPORT_FAILED    = "COURSE_KIT_EXPORT_FAILED"

    # Learning Material Packager — M05 curation
    LEARNING_PACKAGE_CURATION_QUEUED       = "LEARNING_PACKAGE_CURATION_QUEUED"
    LEARNING_PACKAGE_CURATION_COMPLETED    = "LEARNING_PACKAGE_CURATION_COMPLETED"
    LEARNING_PACKAGE_CURATION_FAILED       = "LEARNING_PACKAGE_CURATION_FAILED"
    LEARNING_PACKAGE_CURATION_UNAVAILABLE  = "LEARNING_PACKAGE_CURATION_UNAVAILABLE"

    # Learning Material Packager — M05 RAG indexing
    LEARNING_PACKAGE_RAG_INDEXING_COMPLETED = "LEARNING_PACKAGE_RAG_INDEXING_COMPLETED"
    LEARNING_PACKAGE_RAG_INDEXING_FAILED    = "LEARNING_PACKAGE_RAG_INDEXING_FAILED"

    # Learning Material Packager — M05 faculty item mutations
    LEARNING_PACKAGE_ITEM_ADDED                    = "LEARNING_PACKAGE_ITEM_ADDED"
    LEARNING_PACKAGE_ITEM_REMOVED                  = "LEARNING_PACKAGE_ITEM_REMOVED"
    LEARNING_PACKAGE_ITEM_RECOMMENDATION_TOGGLED   = "LEARNING_PACKAGE_ITEM_RECOMMENDATION_TOGGLED"
    LEARNING_PACKAGE_FACULTY_NOTE_UPLOADED         = "LEARNING_PACKAGE_FACULTY_NOTE_UPLOADED"

    # Learning Material Packager — M05 lifecycle hooks
    LEARNING_PACKAGE_OUTDATED_BY_SYLLABUS_BUMP     = "LEARNING_PACKAGE_OUTDATED_BY_SYLLABUS_BUMP"

    # Labs & Assignment Evaluator — M06 assignment lifecycle
    LAB_ASSIGNMENT_CREATED   = "LAB_ASSIGNMENT_CREATED"
    LAB_ASSIGNMENT_UPDATED   = "LAB_ASSIGNMENT_UPDATED"
    LAB_ASSIGNMENT_PUBLISHED = "LAB_ASSIGNMENT_PUBLISHED"
    LAB_ASSIGNMENT_CLOSED    = "LAB_ASSIGNMENT_CLOSED"
    LAB_ASSIGNMENT_ARCHIVED  = "LAB_ASSIGNMENT_ARCHIVED"

    # Labs & Assignment Evaluator — M06 submission lifecycle
    LAB_SUBMISSION_RECEIVED  = "LAB_SUBMISSION_RECEIVED"
    LAB_SUBMISSION_FLAGGED   = "LAB_SUBMISSION_FLAGGED"   # AI content scan result

    # Labs & Assignment Evaluator — M06 evaluation
    LAB_EVAL_QUEUED          = "LAB_EVAL_QUEUED"
    LAB_EVAL_COMPLETED       = "LAB_EVAL_COMPLETED"
    LAB_EVAL_FAILED          = "LAB_EVAL_FAILED"

    # Labs & Assignment Evaluator — M06 faculty review actions
    LAB_SCORES_UPDATED       = "LAB_SCORES_UPDATED"      # human score override
    LAB_SUBMISSION_RATIFIED  = "LAB_SUBMISSION_RATIFIED"  # grade_ledger written

    # Labs & Assignment Evaluator — M06 moderation report
    LAB_REPORT_REQUESTED     = "LAB_REPORT_REQUESTED"
    LAB_REPORT_COMPLETED     = "LAB_REPORT_COMPLETED"

    # Labs & Assignment Evaluator — M06 evaluator workflow
    LAB_EVALUATOR_ASSIGNED              = "LAB_EVALUATOR_ASSIGNED"
    LAB_EVALUATOR_REMOVED               = "LAB_EVALUATOR_REMOVED"
    LAB_EVALUATOR_OPENED_SUBMISSION     = "LAB_EVALUATOR_OPENED_SUBMISSION"
    LAB_EVALUATOR_SUBMITTED_RECOMMENDATION = "LAB_EVALUATOR_SUBMITTED_RECOMMENDATION"
    LAB_EVALUATOR_AI_REVIEW_TRIGGERED   = "LAB_EVALUATOR_AI_REVIEW_TRIGGERED"

    # Research Supervision — M07 problem lifecycle
    RESEARCH_PROBLEM_SUBMITTED      = "RESEARCH_PROBLEM_SUBMITTED"
    RESEARCH_PROBLEM_EVAL_QUEUED    = "RESEARCH_PROBLEM_EVAL_QUEUED"
    RESEARCH_PROBLEM_AI_EVALUATED   = "RESEARCH_PROBLEM_AI_EVALUATED"
    RESEARCH_PROBLEM_GUIDE_DECIDED  = "RESEARCH_PROBLEM_GUIDE_DECIDED"
    RESEARCH_PROBLEM_AI_GENERATED   = "RESEARCH_PROBLEM_AI_GENERATED"

    # Research Supervision — M07 document lifecycle
    RESEARCH_DOCUMENT_SUBMITTED      = "RESEARCH_DOCUMENT_SUBMITTED"
    RESEARCH_DOCUMENT_EVAL_QUEUED    = "RESEARCH_DOCUMENT_EVAL_QUEUED"
    RESEARCH_DOCUMENT_AI_EVALUATED   = "RESEARCH_DOCUMENT_AI_EVALUATED"
    RESEARCH_DOCUMENT_EVAL_FAILED    = "RESEARCH_DOCUMENT_EVAL_FAILED"
    RESEARCH_DOCUMENT_GUIDE_REVIEWED = "RESEARCH_DOCUMENT_GUIDE_REVIEWED"

    # Research Supervision — M07 viva lifecycle
    VIVA_SESSION_SCHEDULED  = "VIVA_SESSION_SCHEDULED"
    VIVA_SESSION_STARTED    = "VIVA_SESSION_STARTED"
    VIVA_SESSION_COMPLETED  = "VIVA_SESSION_COMPLETED"
    VIVA_AI_EVALUATED       = "VIVA_AI_EVALUATED"
    VIVA_GUIDE_RATIFIED     = "VIVA_GUIDE_RATIFIED"

    # Exam Setter — M08 paper lifecycle
    EXAM_PAPER_CREATED                = "EXAM_PAPER_CREATED"
    EXAM_PAPER_GENERATION_QUEUED      = "EXAM_PAPER_GENERATION_QUEUED"
    EXAM_PAPER_GENERATION_COMPLETED   = "EXAM_PAPER_GENERATION_COMPLETED"
    EXAM_PAPER_GENERATION_FAILED      = "EXAM_PAPER_GENERATION_FAILED"

    # Exam Setter — M08 faculty edits
    EXAM_PAPER_QUESTION_EDITED        = "EXAM_PAPER_QUESTION_EDITED"
    EXAM_PAPER_QUESTION_REPLACED      = "EXAM_PAPER_QUESTION_REPLACED"

    # Exam Setter — M08 human gates
    EXAM_PAPER_SUBMITTED              = "EXAM_PAPER_SUBMITTED"       # Gate 1
    EXAM_PAPER_BOARD_APPROVED         = "EXAM_PAPER_BOARD_APPROVED"  # Gate 2
    EXAM_PAPER_BOARD_RETURNED         = "EXAM_PAPER_BOARD_RETURNED"  # Gate 2 return
    EXAM_PAPER_SEALED                 = "EXAM_PAPER_SEALED"          # Gate 3

    # Exam Setter — M08 release and export
    EXAM_PAPER_RELEASED               = "EXAM_PAPER_RELEASED"
    EXAM_PAPER_AUTO_RELEASED          = "EXAM_PAPER_AUTO_RELEASED"   # Celery ETA task release
    EXAM_PAPER_EXPORTED               = "EXAM_PAPER_EXPORTED"
    EXAM_PAPER_EXPORT_PDF             = "EXAM_PAPER_EXPORT_PDF"

    # Exam Setter — M08 H-35 productization (workflow split + sections + coverage)
    EXAM_PAPER_FACULTY_APPROVED       = "EXAM_PAPER_FACULTY_APPROVED"    # Internal workflow gate
    EXAM_PAPER_SCRUTINIZER_ASSIGNED   = "EXAM_PAPER_SCRUTINIZER_ASSIGNED"
    EXAM_PAPER_SCRUTINIZED            = "EXAM_PAPER_SCRUTINIZED"         # Optional Gate 1.5
    EXAM_PAPER_SECTION_CONFIGURED     = "EXAM_PAPER_SECTION_CONFIGURED"
    EXAM_PAPER_QUESTION_REGENERATED   = "EXAM_PAPER_QUESTION_REGENERATED"
    EXAM_PAPER_CO_COVERAGE_COMPUTED   = "EXAM_PAPER_CO_COVERAGE_COMPUTED"

    # Question Bank — H-35 Addition 1
    QUESTION_BANK_PROMOTED            = "QUESTION_BANK_PROMOTED"    # Question promoted after Board approval

    # Internal Marks — H-35 Addition 2
    INTERNAL_MARKS_SUBMITTED          = "INTERNAL_MARKS_SUBMITTED"  # Faculty submits marks (Gate 1)
    INTERNAL_MARKS_LOCKED             = "INTERNAL_MARKS_LOCKED"     # Dean locks marks (Gate 2)

    # Paper Admin — M09 scan quality check lifecycle (H-36 STEP-02)
    SCRIPT_QUALITY_CHECK_STARTED   = "SCRIPT_QUALITY_CHECK_STARTED"
    SCRIPT_QUALITY_CHECK_COMPLETED = "SCRIPT_QUALITY_CHECK_COMPLETED"
    SCRIPT_QUALITY_CHECK_FAILED    = "SCRIPT_QUALITY_CHECK_FAILED"

    # Paper Admin — M09 OCR pipeline lifecycle (H-36 STEP-03)
    SCRIPT_OCR_STARTED   = "SCRIPT_OCR_STARTED"
    SCRIPT_OCR_COMPLETED = "SCRIPT_OCR_COMPLETED"
    SCRIPT_OCR_FAILED    = "SCRIPT_OCR_FAILED"

    # Paper Admin — M09 script scoring lifecycle
    SCRIPT_SCORING_QUEUED     = "SCRIPT_SCORING_QUEUED"
    SCRIPT_SCORING_COMPLETED  = "SCRIPT_SCORING_COMPLETED"
    SCRIPT_SCORING_FAILED     = "SCRIPT_SCORING_FAILED"

    # Paper Admin — M09 human gates
    SCRIPT_EVALUATOR_ASSIGNED   = "SCRIPT_EVALUATOR_ASSIGNED"
    SCRIPT_MARKS_UPDATED        = "SCRIPT_MARKS_UPDATED"
    SCRIPT_MARKS_SUBMITTED      = "SCRIPT_MARKS_SUBMITTED"      # Gate 1
    SCRIPT_BOARD_FINALISED      = "SCRIPT_BOARD_FINALISED"      # Gate 2
    SCRIPT_QUALITY_OVERRIDDEN   = "SCRIPT_QUALITY_OVERRIDDEN"   # H-36 STEP-12: admin override
    EXAM_SCORE_RECORDED         = "EXAM_SCORE_RECORDED"
    SCRIPT_MODERATION_FLAGGED   = "SCRIPT_MODERATION_FLAGGED"   # M09.2: variance exceeded or manual flag
    SCRIPT_MODERATION_SUBMITTED = "SCRIPT_MODERATION_SUBMITTED" # M09.2: moderator submitted marks
    BOARD_SESSION_CONVENED      = "BOARD_SESSION_CONVENED"      # M09.4: results board session created
    BOARD_SESSION_APPROVED      = "BOARD_SESSION_APPROVED"      # M09.4: board approved results
    BOARD_SESSION_REJECTED      = "BOARD_SESSION_REJECTED"      # M09.4: board rejected results
    RESULTS_DECLARED            = "RESULTS_DECLARED"            # M09.4: admin declared results to students
    REVALUATION_REQUESTED       = "REVALUATION_REQUESTED"       # M09.3: student submitted revaluation
    REVALUATION_ACCEPTED        = "REVALUATION_ACCEPTED"        # M09.3: admin accepted + assigned evaluator
    REVALUATION_REJECTED        = "REVALUATION_REJECTED"        # M09.3: admin rejected at intake
    REVALUATION_MARKS_SUBMITTED = "REVALUATION_MARKS_SUBMITTED" # M09.3: evaluator submitted revaluation marks
    REVALUATION_BOARD_RATIFIED  = "REVALUATION_BOARD_RATIFIED"  # M09.3: board ratified, ledger updated
    REVALUATION_BOARD_REJECTED  = "REVALUATION_BOARD_REJECTED"  # M09.3: board rejected revaluation outcome

    # Digital Exams — M09.5
    DIGITAL_EXAM_SESSION_CREATED   = "DIGITAL_EXAM_SESSION_CREATED"   # admin created session
    DIGITAL_EXAM_SESSION_ACTIVATED = "DIGITAL_EXAM_SESSION_ACTIVATED" # admin opened session to students
    DIGITAL_EXAM_SESSION_CLOSED    = "DIGITAL_EXAM_SESSION_CLOSED"    # admin closed session
    DIGITAL_EXAM_ATTEMPT_STARTED   = "DIGITAL_EXAM_ATTEMPT_STARTED"   # student started attempt
    DIGITAL_EXAM_RESPONSE_SAVED    = "DIGITAL_EXAM_RESPONSE_SAVED"    # student saved answer
    DIGITAL_EXAM_SUBMITTED              = "DIGITAL_EXAM_SUBMITTED"              # student submitted exam
    DIGITAL_EXAM_AUTO_SCORED            = "DIGITAL_EXAM_AUTO_SCORED"            # system auto-scored MCQ
    DIGITAL_EXAM_SUBJECTIVE_SCORED      = "DIGITAL_EXAM_SUBJECTIVE_SCORED"      # faculty scored one subjective response
    DIGITAL_EXAM_SUBJECTIVE_SUBMITTED   = "DIGITAL_EXAM_SUBJECTIVE_SUBMITTED"   # faculty submitted all subjective scores

    # Assignment Engine — M09.6
    ASSIGNMENT_CREATED        = "ASSIGNMENT_CREATED"         # work allocated to an evaluator
    ASSIGNMENT_REASSIGNED     = "ASSIGNMENT_REASSIGNED"      # work moved to a different evaluator
    ASSIGNMENT_STARTED        = "ASSIGNMENT_STARTED"         # evaluator began the work
    ASSIGNMENT_SUBMITTED      = "ASSIGNMENT_SUBMITTED"       # evaluator submitted marks for the work
    ASSIGNMENT_COMPLETED      = "ASSIGNMENT_COMPLETED"       # assignment closed as done (human action)
    ASSIGNMENT_CANCELLED      = "ASSIGNMENT_CANCELLED"       # allocation withdrawn
    AUTO_ASSIGNMENT_EXECUTED  = "AUTO_ASSIGNMENT_EXECUTED"   # workload-balanced batch allocation run

    # OCR Review Queue — M09.7
    OCR_REVIEW_STARTED      = "OCR_REVIEW_STARTED"      # reviewer opened a script for OCR review
    OCR_TEXT_CORRECTED      = "OCR_TEXT_CORRECTED"       # reviewer edited OCR extracted text
    OCR_RERUN_REQUESTED     = "OCR_RERUN_REQUESTED"      # reviewer requested OCR re-extraction
    OCR_ESCALATED           = "OCR_ESCALATED"            # script escalated to Admin for decision
    OCR_ACCEPTED            = "OCR_ACCEPTED"             # OCR text accepted as-is by reviewer
    OCR_MARKED_UNREADABLE   = "OCR_MARKED_UNREADABLE"    # script marked physically unreadable
    OCR_THRESHOLD_UPDATED   = "OCR_THRESHOLD_UPDATED"    # Admin changed confidence threshold config

    # Bell Curve Normaliser — M10
    BELL_CURVE_ANALYSIS_TRIGGERED     = "BELL_CURVE_ANALYSIS_TRIGGERED"
    BELL_CURVE_ANALYSIS_COMPLETED     = "BELL_CURVE_ANALYSIS_COMPLETED"
    BELL_CURVE_ANALYSIS_FAILED        = "BELL_CURVE_ANALYSIS_FAILED"
    BELL_CURVE_NORMALISATION_PREVIEWED = "BELL_CURVE_NORMALISATION_PREVIEWED"
    BELL_CURVE_BOARD_RATIFIED         = "BELL_CURVE_BOARD_RATIFIED"
    BELL_CURVE_REPORT_EXPORTED        = "BELL_CURVE_REPORT_EXPORTED"

    # Subject Assignment — H-31
    SUBJECT_ASSIGNMENT_CREATED = "SUBJECT_ASSIGNMENT_CREATED"
    SUBJECT_ASSIGNMENT_REVOKED = "SUBJECT_ASSIGNMENT_REVOKED"

    # SIS Foundation — M11
    SCHOOL_CREATED = "SCHOOL_CREATED"
    SCHOOL_UPDATED = "SCHOOL_UPDATED"
    SCHOOL_DELETED = "SCHOOL_DELETED"

    # SIS Enrollment — M11-002
    ENROLLMENT_CREATED    = "ENROLLMENT_CREATED"
    ENROLLMENT_UNENROLLED = "ENROLLMENT_UNENROLLED"
    ENROLLMENT_MOVED      = "ENROLLMENT_MOVED"

    # SIS Directory — H50
    STUDENT_PROFILE_UPDATED = "STUDENT_PROFILE_UPDATED"
    FACULTY_PROFILE_UPDATED = "FACULTY_PROFILE_UPDATED"

    # SIS Attendance — H55
    ATTENDANCE_SESSION_CREATED  = "ATTENDANCE_SESSION_CREATED"
    ATTENDANCE_SESSION_UPDATED  = "ATTENDANCE_SESSION_UPDATED"
    ATTENDANCE_MARKED           = "ATTENDANCE_MARKED"
    ATTENDANCE_EDITED           = "ATTENDANCE_EDITED"
    ATTENDANCE_SESSION_REOPENED = "ATTENDANCE_SESSION_REOPENED"

    # SIS Internal Marks — H57 (component-level events)
    INTERNAL_MARKS_COMPONENT_CREATED  = "INTERNAL_MARKS_COMPONENT_CREATED"
    INTERNAL_MARKS_COMPONENT_UPDATED  = "INTERNAL_MARKS_COMPONENT_UPDATED"
    INTERNAL_MARKS_COMPONENT_REOPENED = "INTERNAL_MARKS_COMPONENT_REOPENED"
    INTERNAL_MARKS_ENTERED            = "INTERNAL_MARKS_ENTERED"
    INTERNAL_MARKS_EDITED             = "INTERNAL_MARKS_EDITED"

    # SIS Exam Management — H59
    EXAM_SESSION_PUBLISHED     = "EXAM_SESSION_PUBLISHED"
    EXAM_SESSION_LOCKED        = "EXAM_SESSION_LOCKED"
    EXAM_SESSION_COMPLETED     = "EXAM_SESSION_COMPLETED"
    EXAM_SEATS_ALLOCATED       = "EXAM_SEATS_ALLOCATED"
    EXAM_INVIGILATION_ASSIGNED = "EXAM_INVIGILATION_ASSIGNED"

    # SIS Transcript Generation — H61
    TRANSCRIPT_REQUESTED        = "TRANSCRIPT_REQUESTED"
    TRANSCRIPT_GENERATED        = "TRANSCRIPT_GENERATED"
    TRANSCRIPT_ISSUED           = "TRANSCRIPT_ISSUED"
    TRANSCRIPT_REVOKED          = "TRANSCRIPT_REVOKED"
    TRANSCRIPT_REGENERATED      = "TRANSCRIPT_REGENERATED"
    TRANSCRIPT_VERIFIED         = "TRANSCRIPT_VERIFIED"
    TRANSCRIPT_PDF_DOWNLOADED   = "TRANSCRIPT_PDF_DOWNLOADED"

    # SIS Graduation Audit — H62
    GRADUATION_AUDIT_TRIGGERED        = "GRADUATION_AUDIT_TRIGGERED"
    GRADUATION_AUDIT_SUBMITTED        = "GRADUATION_AUDIT_SUBMITTED"
    GRADUATION_AUDIT_REGENERATED      = "GRADUATION_AUDIT_REGENERATED"
    GRADUATION_AUDIT_BOARD_APPROVED   = "GRADUATION_AUDIT_BOARD_APPROVED"
    GRADUATION_CANDIDATE_OVERRIDDEN   = "GRADUATION_CANDIDATE_OVERRIDDEN"
    GRADUATION_CANDIDATE_RATIFIED     = "GRADUATION_CANDIDATE_RATIFIED"
    GRADUATION_CANDIDATE_DEFERRED     = "GRADUATION_CANDIDATE_DEFERRED"
    GRADUATION_CERTIFICATE_ISSUED     = "GRADUATION_CERTIFICATE_ISSUED"
    GRADUATION_CERTIFICATE_REVOKED    = "GRADUATION_CERTIFICATE_REVOKED"
    GRADUATION_PROVISIONAL_CONFIRMED  = "GRADUATION_PROVISIONAL_CONFIRMED"
    GRADUATION_CERTIFICATE_VERIFIED   = "GRADUATION_CERTIFICATE_VERIFIED"


class AuditLog(Base):
    __tablename__ = "audit_logs"
    __table_args__ = (
        Index("ix_audit_logs_tenant_created",  "tenant_id",     "created_at"),
        Index("ix_audit_logs_event_created",   "event_type",    "created_at"),
        Index("ix_audit_logs_actor_created",   "actor_user_id", "created_at"),
        Index("ix_audit_logs_created",         "created_at"),
        {"schema": "public"},
    )

    id            = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    event_type    = Column(String, nullable=False)
    actor_user_id = Column(UUID(as_uuid=True), nullable=True)
    actor_role    = Column(String, nullable=True)
    tenant_id     = Column(
        UUID(as_uuid=True),
        ForeignKey("public.tenants.id", ondelete="SET NULL"),
        nullable=True,
    )
    schema_name   = Column(String, nullable=True)
    target_entity = Column(String, nullable=True)
    target_id     = Column(String, nullable=True)
    metadata_     = Column("metadata", JSONB, nullable=True)
    ip_address    = Column(String, nullable=True)
    user_agent    = Column(String, nullable=True)
    created_at    = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
