"""
M07 Research Supervision — SQLAlchemy models.

Tables (all tenant-schema, no schema= kwarg):
  research_problems   — student-proposed or guide-offered research problems
  research_documents  — versioned documents uploaded per research problem
  viva_sessions       — AI-conducted video viva session per document

Human-gate invariants:
  research_problems.status → ACCEPTED/REJECTED only via guide decision endpoint.
  research_documents.status → APPROVED/REVISION_REQUESTED only via guide review endpoint.
  viva_sessions.status → GUIDE_RATIFIED only via guide ratify endpoint.
  guide_evaluation is NEVER written by any Celery task.

Tenant isolation: all tables live in the tenant schema.
"""
from __future__ import annotations

import enum
import uuid

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, Float,
    ForeignKey, Index, Integer, Numeric, String, Text,
    UniqueConstraint, text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.database import Base


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ProblemSource(str, enum.Enum):
    STUDENT_PROPOSED = "STUDENT_PROPOSED"
    AI_GENERATED     = "AI_GENERATED"


class ProblemStatus(str, enum.Enum):
    DRAFT              = "DRAFT"            # AI-generated, not yet offered to student
    PENDING_REVIEW     = "PENDING_REVIEW"   # student submitted; awaiting guide decision
    ACCEPTED           = "ACCEPTED"         # guide accepted
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REJECTED           = "REJECTED"


class AIRecommendation(str, enum.Enum):
    ACCEPT = "ACCEPT"
    REVISE = "REVISE"
    REJECT = "REJECT"


class GuideDecision(str, enum.Enum):
    ACCEPT = "ACCEPT"
    REVISE = "REVISE"
    REJECT = "REJECT"


class DocumentStatus(str, enum.Enum):
    SUBMITTED          = "SUBMITTED"
    EVALUATING         = "EVALUATING"
    EVALUATED          = "EVALUATED"
    GUIDE_REVIEWED     = "GUIDE_REVIEWED"
    APPROVED           = "APPROVED"
    REVISION_REQUESTED = "REVISION_REQUESTED"


class VivaStatus(str, enum.Enum):
    SCHEDULED      = "SCHEDULED"
    IN_PROGRESS    = "IN_PROGRESS"
    COMPLETED      = "COMPLETED"      # recording uploaded, awaiting ASR
    ASR_PROCESSING = "ASR_PROCESSING" # Whisper + LLM evaluation running
    EVALUATED      = "EVALUATED"      # AI evaluation written; awaiting guide
    GUIDE_RATIFIED = "GUIDE_RATIFIED" # guide ratified — final


# ---------------------------------------------------------------------------
# ResearchProblem
# ---------------------------------------------------------------------------

class ResearchProblem(Base):
    """
    One research problem: either student-proposed or AI-generated by the guide.

    research_questions JSONB schema:
      [{question: str}]  — 1–5 research questions

    Human-gate: status transitions to ACCEPTED / REVISION_REQUESTED / REJECTED
    only via the guide decision endpoint. Celery tasks write only AI scores.
    """
    __tablename__ = "research_problems"
    __table_args__ = (
        Index("ix_research_problems_guide",   "guide_user_id"),
        Index("ix_research_problems_student", "student_user_id"),
        Index("ix_research_problems_status",  "status"),
        Index("ix_research_problems_source",  "source"),
        Index("ix_research_problems_created", "created_at"),
    )

    id                  = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Guide who owns / will supervise this problem
    guide_user_id       = Column(UUID(as_uuid=True), nullable=False)
    # Null for AI_GENERATED problems until a student is assigned
    student_user_id     = Column(UUID(as_uuid=True), nullable=True)

    title               = Column(String, nullable=False)
    abstract            = Column(Text, nullable=True)

    # [{question: str}]
    research_questions  = Column(JSONB, nullable=False, server_default="[]")

    source              = Column(
        Enum(ProblemSource, native_enum=False),
        nullable=False,
        default=ProblemSource.STUDENT_PROPOSED,
    )

    # AI evaluation outputs — written by Celery task only
    novelty_score       = Column(Numeric(4, 3), nullable=True)   # 0–1
    feasibility_score   = Column(Numeric(4, 3), nullable=True)   # 0–1
    clarity_score       = Column(Numeric(4, 3), nullable=True)   # 0–1
    ai_recommendation   = Column(
        Enum(AIRecommendation, native_enum=False),
        nullable=True,
    )
    ai_reasoning        = Column(Text, nullable=True)

    # AI provenance
    ai_model            = Column(String, nullable=True)
    prompt_hash         = Column(String, nullable=True)

    # FK to public.task_jobs for the evaluation Celery task
    eval_job_id         = Column(UUID(as_uuid=True), nullable=True)

    # Workflow status
    status              = Column(
        Enum(ProblemStatus, native_enum=False),
        nullable=False,
        default=ProblemStatus.PENDING_REVIEW,
    )

    # Guide decision — written ONLY by guide decision endpoint (human gate)
    guide_decision      = Column(
        Enum(GuideDecision, native_enum=False),
        nullable=True,
    )
    guide_note          = Column(Text, nullable=True)
    decided_at          = Column(DateTime(timezone=True), nullable=True)

    created_at          = Column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at          = Column(DateTime(timezone=True), nullable=True)

    documents = relationship(
        "ResearchDocument",
        back_populates="problem",
        cascade="all, delete-orphan",
        order_by="ResearchDocument.version",
    )
    viva_sessions = relationship(
        "VivaSession",
        back_populates="problem",
        cascade="all, delete-orphan",
    )


# ---------------------------------------------------------------------------
# ResearchDocument
# ---------------------------------------------------------------------------

class ResearchDocument(Base):
    """
    One versioned document upload per research problem.

    evaluation_report JSONB schema:
      {
        format_issues:     [{section: str, issue: str}],
        plagiarism_matches: [{source: str, similarity: float, excerpt: str}],
        ai_highlights:     [{start: int, end: int, score: float}],
        clarity_notes:     str,
      }

    Human-gate: status APPROVED / REVISION_REQUESTED written only via guide
    review endpoint. Celery task writes only up to EVALUATED.
    """
    __tablename__ = "research_documents"
    __table_args__ = (
        Index("ix_research_documents_problem",  "research_problem_id"),
        Index("ix_research_documents_student",  "student_user_id"),
        Index("ix_research_documents_status",   "status"),
        Index("ix_research_documents_version",  "research_problem_id", "version"),
    )

    id                    = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    research_problem_id   = Column(
        UUID(as_uuid=True),
        ForeignKey("research_problems.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Denormalized for fast queries without joining to research_problems
    student_user_id       = Column(UUID(as_uuid=True), nullable=False)

    version               = Column(Integer, nullable=False, default=1)

    # S3 object key
    file_url              = Column(String, nullable=True)
    file_name             = Column(String, nullable=True)

    # AI evaluation scores — written by Celery task only
    plagiarism_score      = Column(Float, nullable=True)    # max similarity 0–1
    ai_content_score      = Column(Float, nullable=True)    # 0–1
    format_score          = Column(Float, nullable=True)    # 0–1 (1 = fully compliant)
    clarity_score         = Column(Float, nullable=True)    # 0–1

    # Full structured evaluation report
    evaluation_report     = Column(JSONB, nullable=True)

    # AI provenance
    ai_model              = Column(String, nullable=True)
    prompt_hash           = Column(String, nullable=True)

    eval_job_id           = Column(UUID(as_uuid=True), nullable=True)

    status                = Column(
        Enum(DocumentStatus, native_enum=False),
        nullable=False,
        default=DocumentStatus.SUBMITTED,
    )

    # Guide review — written ONLY by guide review endpoint (human gate)
    guide_comment         = Column(Text, nullable=True)
    guide_reviewed_at     = Column(DateTime(timezone=True), nullable=True)

    submitted_at          = Column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    problem = relationship("ResearchProblem", back_populates="documents")
    viva_sessions = relationship(
        "VivaSession",
        back_populates="document",
        cascade="all, delete-orphan",
    )


# ---------------------------------------------------------------------------
# VivaSession
# ---------------------------------------------------------------------------

class VivaSession(Base):
    """
    One async video viva session per student per document.

    Async viva design: student records video responses within a session window
    (expires_at). Questions are pre-generated from the document. Follow-up
    questions added after each base answer. Celery processes recording via
    Whisper ASR + LLM evaluation.

    ai_questions JSONB schema:
      [{id: str, text: str, source: "base"|"followup",
        based_on_qid: str|null, order: int}]

    ai_responses JSONB schema:
      [{question_id: str, response_text: str,
        start_ms: int|null, end_ms: int|null}]

    ai_evaluation JSONB schema (written by Celery only):
      [{question_id: str, coherence: float, accuracy: float,
        depth: float, comment: str}]

    guide_evaluation JSONB schema (written ONLY by guide ratify endpoint):
      [{question_id: str, score_override: float|null, comment: str|null}]

    Human-gate: status → GUIDE_RATIFIED and guide_evaluation only written via
    the guide ratify endpoint. overall_guide_score computed and stored there.
    """
    __tablename__ = "viva_sessions"
    __table_args__ = (
        UniqueConstraint("session_token", name="uq_viva_sessions_token"),
        Index("ix_viva_sessions_problem",    "research_problem_id"),
        Index("ix_viva_sessions_document",   "document_id"),
        Index("ix_viva_sessions_student",    "student_user_id"),
        Index("ix_viva_sessions_guide",      "guide_user_id"),
        Index("ix_viva_sessions_token",      "session_token"),
        Index("ix_viva_sessions_status",     "status"),
        Index("ix_viva_sessions_scheduled",  "scheduled_at"),
    )

    id                    = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    research_problem_id   = Column(
        UUID(as_uuid=True),
        ForeignKey("research_problems.id", ondelete="CASCADE"),
        nullable=False,
    )
    document_id           = Column(
        UUID(as_uuid=True),
        ForeignKey("research_documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    student_user_id       = Column(UUID(as_uuid=True), nullable=False)
    guide_user_id         = Column(UUID(as_uuid=True), nullable=False)

    # Time-limited session access token
    session_token         = Column(String, nullable=False, unique=True)

    # AI-generated questions (written by schedule endpoint via viva_engine)
    ai_questions          = Column(JSONB, nullable=False, server_default="[]")

    # Student responses (written incrementally during session)
    ai_responses          = Column(JSONB, nullable=False, server_default="[]")

    # S3 path of combined recording upload
    video_url             = Column(String, nullable=True)
    transcript            = Column(Text, nullable=True)

    # AI evaluation — written ONLY by Celery process_viva_session task
    ai_evaluation         = Column(JSONB, nullable=True)
    overall_ai_score      = Column(Numeric(5, 2), nullable=True)

    # Guide evaluation — written ONLY by guide ratify endpoint (human gate)
    guide_evaluation      = Column(JSONB, nullable=True)
    overall_guide_score   = Column(Numeric(5, 2), nullable=True)

    # DPDP Act 2023 compliance — explicit student consent before recording
    consent_recorded      = Column(Boolean, nullable=False, default=False)

    # AI provenance
    ai_model              = Column(String, nullable=True)

    eval_job_id           = Column(UUID(as_uuid=True), nullable=True)

    scheduled_at          = Column(DateTime(timezone=True), nullable=True)
    expires_at            = Column(DateTime(timezone=True), nullable=True)
    completed_at          = Column(DateTime(timezone=True), nullable=True)
    ratified_at           = Column(DateTime(timezone=True), nullable=True)

    status                = Column(
        Enum(VivaStatus, native_enum=False),
        nullable=False,
        default=VivaStatus.SCHEDULED,
    )

    problem  = relationship("ResearchProblem", back_populates="viva_sessions")
    document = relationship("ResearchDocument", back_populates="viva_sessions")
